export './home.dart';
export './feeds.dart';
export 'profile.dart';
export './options.dart';
export './splash.dart';
export './reminder.dart';
export 'training.dart';
export './my_plan.dart';
// auth
