export './home.dart';
export './feeds.dart';
export 'profile.dart';
export './options.dart';
export './splash.dart';
export './reminder.dart';
export 'training.dart';
export './my_plan.dart';
export './exercise_type.dart';
export './feed_detail.dart';
// auth
export 'auth/age.dart';
export 'auth/gender.dart';
export 'auth/height.dart';
export 'auth/weight.dart';
